BS-3673: Create python client library
build-security/opa-python-client pull request #1
Opened 2021-05-13 09:21 UTC by yashtewari

2021-05-13 10:14 UTC, eyalkraft requested changes

2021-05-13 10:14 UTC, eyalkraft commented on pdp/client.py
> +        if res.json() is True:
wouldn't this be `{"result" : True}`?

2021-05-13 10:16 UTC, eyalkraft commented on pdp/client.py
> +        if res.json() is True:
also looking into the implementation looks like this might through a `ValueError` exception. this should be handled as well.

2021-05-19 11:02 UTC, yashtewari commented on pdp/client.py
> +        if not ('://' in self.hostname):
I considered it but it's not great for the automagic we're doing here

2021-05-20 08:24 UTC, yashtewari commented on pdp/client.py
> +        if res.json() is True:
Nice catch! Fixed

2021-05-24 08:42 UTC, eyalkraft approved these changes
Good work.
I think an example application using the middleware could be very helpful here,
and worth the time doing it if you have some more time for this task.
you can check out my (under-construction) repo https://github.com/build-security/opa-production-example

2021-05-26 11:55 UTC, merged